import * as vscode from 'vscode';
import { IGenerateTestScaffoldInput } from './toolInputs';

/**
 * Tool: sql_agents_generate_test_scaffold
 *
 * Generates the framework boilerplate for a SQL unit test suite.
 * This establishes the structural skeleton before the LLM fills in the assertions.
 */
export class GenerateTestScaffoldTool
  implements vscode.LanguageModelTool<IGenerateTestScaffoldInput>
{
  async prepareInvocation(
    options: vscode.LanguageModelToolInvocationPrepareOptions<IGenerateTestScaffoldInput>,
    _token: vscode.CancellationToken
  ): Promise<vscode.PreparedToolInvocation> {
    const { object_name, dialect } = options.input;
    const frameworkName =
      dialect === 'tsql'
        ? 'tSQLt'
        : dialect === 'postgresql'
        ? 'pgTAP'
        : 'generic SQL assertions';

    return {
      invocationMessage: `Generating ${frameworkName} test scaffold for ${object_name}...`,
      confirmationMessages: {
        title: 'Generate Test Scaffold',
        message: new vscode.MarkdownString(
          `Generate a **${frameworkName}** test scaffold for \`${object_name}\`?\n\n` +
          `This creates the boilerplate structure: test class, setup/teardown, and stub test procedures.`
        ),
      },
    };
  }

  async invoke(
    options: vscode.LanguageModelToolInvocationOptions<IGenerateTestScaffoldInput>,
    _token: vscode.CancellationToken
  ): Promise<vscode.LanguageModelToolResult> {
    const { object_name, dialect, test_count = 5 } = options.input;

    if (!object_name || object_name.trim().length === 0) {
      throw new Error(
        'object_name is required. Provide the name of the SQL object to test, ' +
        'e.g. "usp_TransferFunds" or "vw_MonthlySales".'
      );
    }

    let scaffold: string;

    // ── T-SQL / tSQLt scaffold ────────────────────────────────────────────
    if (dialect === 'tsql') {
      const testClass = `[${object_name}_Tests]`;
      const stubs = Array.from({ length: test_count }, (_, i) => {
        const names = [
          'HappyPath_ReturnsExpectedResult',
          'NullInput_ThrowsExpectedError',
          'EmptySet_ReturnsZeroRows',
          'BoundaryValue_MaxInput_Succeeds',
          'InvalidInput_FailsWithMeaningfulError',
          'DuplicateKey_RaisesConstraintViolation',
          'LargeDataSet_CompletesWithinTimeout',
        ];
        return `-- ──────────────────────────────────────────────────────────────────\nCREATE OR ALTER PROCEDURE ${testClass}.[test_${names[i] ?? `Scenario${i + 1}`}]\nAS\nBEGIN\n    -- ARRANGE\n    EXEC tSQLt.FakeTable @TableName = 'dbo.YourTableName'; -- TODO: specify table\n    INSERT INTO dbo.YourTableName (Col1, Col2) VALUES ('test_value', 42);\n\n    -- ACT\n    EXEC dbo.${object_name}; -- TODO: add parameters\n\n    -- ASSERT\n    EXEC tSQLt.AssertEquals @Expected = 1, @Actual = 1; -- TODO: replace with real assertion\nEND;\nGO\n`;
      });

      scaffold = [
        `-- =============================================================`,
        `-- tSQLt Test Suite: ${object_name}`,
        `-- Framework:        tSQLt (SQL Server Unit Testing)`,
        `-- Object Under Test: dbo.${object_name}`,
        `-- Generated by:     SQL Agents Extension (April 2026 pattern)`,
        `-- =============================================================`,
        ``,
        `-- STEP 1: Install tSQLt if not already installed`,
        `-- EXEC tSQLt.NewTestClass '${object_name}_Tests';`,
        ``,
        `-- STEP 2: Create the test class`,
        `EXEC tSQLt.NewTestClass @ClassName = '${object_name}_Tests';`,
        `GO`,
        ``,
        `-- STEP 3: Test procedures`,
        ...stubs,
        ``,
        `-- STEP 4: Run all tests in the class`,
        `-- EXEC tSQLt.Run '${object_name}_Tests';`,
        ``,
        `-- STEP 5: Run ALL tests`,
        `-- EXEC tSQLt.RunAll;`,
      ].join('\n');

    // ── PostgreSQL / pgTAP scaffold ───────────────────────────────────────
    } else if (dialect === 'postgresql') {
      const stubs = Array.from({ length: test_count }, (_, i) => {
        const names = [
          'happy_path_returns_expected_result',
          'null_input_raises_exception',
          'empty_set_returns_zero_rows',
          'boundary_value_max_input_succeeds',
          'invalid_input_fails_gracefully',
        ];
        return `-- Test ${i + 1}: ${names[i] ?? `scenario_${i + 1}`}\nSELECT ok(\n    (SELECT /* your assertion here */ 1 = 1),\n    '${names[i] ?? `scenario_${i + 1}`}'\n);`;
      }).join('\n\n');

      scaffold = [
        `-- =============================================================`,
        `-- pgTAP Test Suite: ${object_name}`,
        `-- Framework:        pgTAP (PostgreSQL Unit Testing)`,
        `-- Object Under Test: public.${object_name}`,
        `-- Generated by:     SQL Agents Extension (April 2026 pattern)`,
        `-- Run with: pg_prove -d yourdb test_${object_name}.sql`,
        `-- =============================================================`,
        ``,
        `BEGIN;`,
        ``,
        `SELECT plan(${test_count}); -- TODO: update count to match actual tests`,
        ``,
        `-- ── SETUP ──────────────────────────────────────────────────────`,
        `CREATE TEMP TABLE test_data (`,
        `    id SERIAL PRIMARY KEY,`,
        `    col1 TEXT,`,
        `    col2 INTEGER`,
        `);`,
        ``,
        `-- Seed test data`,
        `INSERT INTO test_data (col1, col2) VALUES ('test', 42);`,
        ``,
        `-- ── TESTS ──────────────────────────────────────────────────────`,
        stubs,
        ``,
        `-- ── TEARDOWN ────────────────────────────────────────────────────`,
        `DROP TABLE IF EXISTS test_data;`,
        ``,
        `SELECT * FROM finish();`,
        `ROLLBACK;`,
      ].join('\n');

    // ── Generic / framework-agnostic scaffold ─────────────────────────────
    } else {
      const stubs = Array.from({ length: test_count }, (_, i) => [
        `-- ── TEST ${i + 1}: Scenario description ─────────────────────────────`,
        `-- SETUP: Insert test data`,
        `-- INSERT INTO test_table (...) VALUES (...);`,
        ``,
        `-- ACT: Execute the object`,
        `-- EXEC / CALL / SELECT from ${object_name};`,
        ``,
        `-- ASSERT: Verify the result`,
        `-- SELECT CASE WHEN actual_value = expected_value`,
        `--             THEN 'PASS' ELSE 'FAIL' END AS test_result;`,
        ``,
      ].join('\n')).join('\n');

      scaffold = [
        `-- =============================================================`,
        `-- SQL Test Suite: ${object_name}`,
        `-- Framework:      Framework-Agnostic Assertion Script`,
        `-- Generated by:   SQL Agents Extension (April 2026 pattern)`,
        `-- =============================================================`,
        ``,
        `-- ── SETUP ──────────────────────────────────────────────────────`,
        `BEGIN TRANSACTION; -- Wrap in transaction; ROLLBACK after tests`,
        ``,
        `-- Create test isolation table (if applicable)`,
        `CREATE TABLE #TestResults (TestName VARCHAR(200), Result VARCHAR(10), Details VARCHAR(500));`,
        ``,
        stubs,
        ``,
        `-- ── REPORT ──────────────────────────────────────────────────────`,
        `SELECT * FROM #TestResults ORDER BY Result;`,
        ``,
        `ROLLBACK TRANSACTION; -- Clean up all test data`,
      ].join('\n');
    }

    return new vscode.LanguageModelToolResult([
      new vscode.LanguageModelTextPart(scaffold),
    ]);
  }
}
